name: 'Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install dependecies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Apply infrastructure
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_comment: false
          tf_actions_version: latest
          tg_actions_version: v0.31.8
          tf_actions_working_dir: iac
          tf_actions_subcommand: apply
          args: --terragrunt-non-interactive tfplan
